export const ROUTE = {
  DASHBOARD: "/dashboard",
  DASHBOARD_CATEGORY: "/dashboard/category",
  DASHBOARD_POST: "/dashboard/post",
  DASHBOARD_BANNER: "/dashboard/banner",
  LOGIN: "login",
  HOME: "/",
  LIST_POST: "/dashboard/post",
  CREATE_POST: "/dashboard/post/new",
  EDIT_POST: "/dashboard/post/{slug}/edit",
  EDIT_BANNER: "/dashboard/banner/:id/edit",
  NEW_BANNER: "/dashboard/banner/new",
  NEWS_DETAILS: "/news/:slug",
  PROMOTIONS: "/promotions",
  DASHBOARD_PROMOTIONS: "/dashboard/promotions",
  DASHBOARD_PROMOTIONS_EDIT: "/dashboard/promotions/:id/edit",
  DASHBOARD_PROMOTIONS_NEW: "/dashboard/promotions/new",
  STORY_DETAILS: "/story/:slug",
  FEEDBACK: "/feedback",
};
